name: database_service
description: A database broker for no-sql and sql databases
version: 3.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.2
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.12
  drift_dev: ^2.20.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
