name: database_service_wrapper
description: A unified Flutter database service wrapper supporting SQL (Drift, Sqflite), NoSQL (Hive, ObjectBox), and secure storage with a consistent API
version: 1.0.0

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  drift: 2.28.0
  drift_flutter: 0.2.5
  flutter:
    sdk: flutter
  flutter_secure_storage: 9.2.4
  hive: 2.2.3
  hive_flutter: 1.1.0
  objectbox: 4.3.1
  objectbox_flutter_libs: 4.3.1
  path: 1.9.1
  path_provider: 2.1.5
  sqflite: 2.4.2
  sqflite_common_ffi: 2.3.6
  sqflite_common_ffi_web: 1.0.1+1

dev_dependencies:
  build_runner: 2.7.1
  drift_dev: 2.28.1
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  objectbox_generator: 4.3.1
