name: database_service
description: A new Flutter package project.
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^7.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter: null
