name: database_service
description: A database broker for no-sql and sql databases
version: 3.0.4

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  drift: 2.21.0
  drift_flutter: 0.2.1
  flutter:
    sdk: flutter
  flutter_secure_storage: 9.2.2
  hive: 2.2.3
  hive_flutter: 1.1.0
  path: 1.9.1
  path_provider: 2.1.4
  sqflite: 2.4.0
  sqflite_common_ffi: 2.3.4

dev_dependencies:
  build_runner: 2.4.13
  drift_dev: 2.21.2
  flutter_test:
    sdk: flutter
  lint: 2.3.0
